### ISSUE TITLE
I believe the Southeastern SS Minion in last zone needs to be moved a little bit north

### ISSUE THREAD

**Issue by Hezkezl** [RKI027/ffxiv-huntmaps#2]
Currently it's centered at ~X:22.7 - Y:34.6 (on the side of a mountain), when it should be moved north a little, centered closer to X:22.7 - Y:32.1 (near a tall pillar of rock.)

Just had the SS spawn for me on Behemoth and that was roughly where it was at. The others seemed okay though. (Possible that the dot on the map is correct but the group that went southeast dragged him away a bit because when I got there he was at 10%, but yea)

**Comment by RKI027** [comment]
Ah indeed, seems like Faloop moved this one to 23.4, 33.1 so will adjust to that
