### ISSUE TITLE
Misplaced B rank (Mare Lamentorum)

### ISSUE THREAD

**Issue by Scylune** [RKI027/ffxiv-huntmaps#3]
Hi :)

I found my Genesis Rock at Daphnia's spot ^^
![image](https://user-images.githubusercontent.com/63762626/155844367-80f0768e-f4ba-4378-919f-c62624d48c40.png)

Idk if both can be there or if it's just an error.

Ty anyway 👍

**Comment by RKI027** [comment]
Thanks for noticing, one spot of Daphnia was swapped with Genesis indeed. Fixed with da85b7d (release incoming)

**Comment by Scylune** [comment]
Thank you :)
