### ISSUE TITLE
UTF-8 name encode ?

### ISSUE THREAD

**Issue by Scylune** [RKI027/ffxiv-huntmaps#4]
Hi :)

I found a weird name on the map, maybe an UTF-8 encode error : 

![b rank](https://user-images.githubusercontent.com/63762626/159339420-d6d16dea-ecfd-466a-a213-091541aaa2d8.jpg)

Ü-u-ü-u

Ofc no emergency xD Ty !

**Comment by RKI027** [comment]
Thanks for reporting. Indeed, was due to UTF-8 encoding. Fixed with 8e06176 and in release `v0.4.6`

**Comment by Scylune** [comment]
Thank you :)
