### ISSUE TITLE
Loporrits Tribal area ^^

### ISSUE THREAD

**Issue by Scylune** [RKI027/ffxiv-huntmaps#5]
Hey ^^ I hope your're well :)

We've got some new tribal this tuesday.
No need to rush if you're busy, but if you find some free time to update the moon map : 

![image](https://user-images.githubusercontent.com/63762626/224171062-9c9f3926-ee4d-42ea-87b0-289512cb0a70.png)

Thank you !

**Comment by RKI027** [comment]
Updated and released [here](https://github.com/RKI027/ffxiv-huntmaps/releases/tag/v0.4.8)

**Comment by Scylune** [comment]
Thank you <3
