### ISSUE TITLE
No change to kozamu'ka map

### ISSUE THREAD

**Issue by ArcaneInferno** [RKI027/ffxiv-huntmaps#6]
Hi,

I downloaded the latest version (v7.1.0) but the map on kozama'uka doesn't seem to have change to the S/A/B/ location nor it is shows the outlines of the tribes that around the area on the map.

Thanks

**Comment by burnnie** [comment]
Hi,

can confirm this issue. Nechuciho's name is also not fixed in the modpack.

**Comment by RKI027** [comment]
Thanks for the notice. Fixed in [v7.1.1](https://github.com/RKI027/ffxiv-huntmaps/releases/tag/v7.1.1)
